{
 "title": "AggreGator",
 "time": { "from": "now/M", "to": "now" },
 "templating": {
  "list": [
   { "name": "epoch", "query": "${VAR_EPOCH}" }
  ]
 },
 "panels": [
  { "title": "Snapshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "🚧[WIP] Net Worth🚧",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT date, sum(adjusted_close), -sum(adjusted_close) as negative, 0.5*sum(adjusted_close) as net\nFROM market\nWHERE\n  $__timeFilter(date)\ngroup by date\norder by date"
    }
   ]
  },
  {
   "title": "🚧[WIP] 五月雨🚧",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select 'Savings' as fund, 250000.00 as savings"
    },
    {
     "rawSql": "select 'SPDR' as fund, 500000.00 as spdr"
    },
    {
     "rawSql": "select 'REIT' as fund, 750000.00 as reit"
    }
   ]
  },
  {
   "title": "🚧[WIP] Buckets?🚧",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select 'Bills' as fund, 250000.00 as savings"
    },
    {
     "rawSql": "select 'Stuff' as fund, 500000.00 as spdr"
    },
    {
     "rawSql": "select 'Misc' as fund, 750000.00 as reit"
    }
   ]
  },
  {
   "title": "🚧[WIP] Balance Summary🚧",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  adjusted_close\nFROM market\nWHERE\n  $__timeFilter(date)\nORDER BY date"
    }
   ]
  },
  { "title": "Portfolio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Allocations",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select shares.symbol, quantity * adjusted_close\r\nfrom (\r\n  select symbol, quantity\r\n  from (\r\n    select symbol, SUM(quantity) as quantity\r\n    from trades\r\n    where date < '${__to:date}'\r\n    group by symbol\r\n  ) as totals\r\n  where quantity > 0\r\n) as shares\r\njoin (\r\n  select distinct on (symbol) symbol, adjusted_close\r\n  from market\r\n  where date < '${__to:date}'\r\n  order by symbol, date DESC\r\n) as current_prices\r\non shares.symbol = current_prices.symbol"
    }
   ]
  },
  {
   "title": "Portfolio Performance",
   "type": "timeseries",
   "description": "Amount invested vs Portfolio Value",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select time, amount as \"Amount Invested\"\r\nfrom (\r\n    select time_bucket_gapfill('1 day', date) as time, locf(max(value)) as amount\r\n    from (\r\n      select date, SUM(invested) over (order by date) as value\r\n      from (\r\n        select trades.date, SUM(trades.quantity * lots.price) as invested\r\n        from trades\r\n        join lots on lots.id=trades.lot_id\r\n        where trades.date < '${__to:date}'\r\n        group by trades.date\r\n        order by trades.date\r\n      ) as invested_over_time\r\n    ) as cumulative\r\n    where date between '${epoch:date}' and '${__to:date}'\r\n    group by time\r\n    order by time\r\n) as history\r\nwhere $__timeFilter(time)"
    },
    {
     "rawSql": "select time, value as \"Portfolio Value\"\r\nfrom (\r\n    select time, sum(qty * price) as value\r\n    from (\r\n        select time_bucket_gapfill('1 day', date) as time, symbol, locf(min(qty)) as qty\r\n        from (\r\n            select date, symbol, SUM(quantity) over (partition by symbol order by date) as qty\r\n            from trades\r\n            where date < '${__to:date}'\r\n            order by date\r\n        ) as cumulatives\r\n        where date between '${epoch:date}' and '${__to:date}'\r\n        group by time, symbol\r\n        order by time\r\n    ) as assets\r\n    join (\r\n      select time_bucket_gapfill('1 day', date) as gapfill_date, symbol, locf(min(adjusted_close)) as price\r\n      from market\r\n      where date between '${epoch:date}' and '${__to:date}'\r\n      group by gapfill_date, symbol\r\n      order by gapfill_date\r\n    ) as extended_market\r\n    on assets.symbol=extended_market.symbol and assets.time=extended_market.gapfill_date\r\n    where qty is not null\r\n    group by time\r\n    order by time\r\n) as history\r\nwhere $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "ROI",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select ((current_value - total_cost) / total_cost) as percent_gl, (current_value - total_cost) as total_gl\r\nfrom (\r\n    select SUM(total_cost) as total_cost, SUM(quantity * price) as current_value\r\n    from (\r\n        select trades.symbol, SUM(quantity) as quantity, SUM(quantity * lots.price) as total_cost\r\n        from trades\r\n        join lots on lots.id=trades.lot_id\r\n        where trades.date < '${__to:date}'\r\n        group by trades.symbol\r\n    ) as interm\r\n    join (\r\n        select distinct on (symbol) symbol, adjusted_close as price\r\n        from market\r\n        where date <= '${__to:date}'\r\n        order by symbol, date DESC\r\n    ) as current_prices\r\n    on interm.symbol=current_prices.symbol\r\n    where quantity > 0\r\n) as calcd\r\n"
    }
   ]
  },
  {
   "title": "Deltas",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "with total as (\r\n    select SUM(quantity) as qty\r\n    from trades\r\n    where date <= '${__to:date}'\r\n)\r\n\r\nselect symbol as \"Symbol\", (percent_change * quantity / total.qty) as \"Impact\", percent_change as \"%Δ\", change_per_share as \"$Δ per share\", total_change as \"Total $Δ\"\r\nfrom (\r\n  select symbol, quantity,((current_value - total_cost) / total_cost) as percent_change, (current_price_per_share - avg_cost_per_share) as change_per_share, (current_value - total_cost) as total_change\r\n  from (\r\n      select interm.symbol, quantity, total as total_cost, (quantity * price) as current_value, (total / quantity) as avg_cost_per_share, price as current_price_per_share\r\n      from (\r\n          select trades.symbol, SUM(quantity) as quantity, SUM(quantity * lots.price) as total\r\n          from trades\r\n          join lots on lots.id=trades.lot_id\r\n          where trades.date <= '${__to:date}'\r\n          group by trades.symbol\r\n      ) as interm\r\n      join (\r\n          select distinct on (symbol) symbol, adjusted_close as price\r\n          from market\r\n          where date <= '${__to:date}'\r\n          order by symbol, date DESC\r\n      ) as current_prices\r\n      on interm.symbol=current_prices.symbol\r\n      where quantity > 0\r\n  ) as calcd\r\n) as calcd2 , total\r\norder by \"Impact\" desc"
    }
   ]
  },
  { "title": "Cash Flow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "🚧[WIP] Expenses🚧",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select shares.symbol, quantity * adjusted_close\r\nfrom (\r\n  select symbol, quantity\r\n  from (\r\n    select symbol, SUM(quantity) as quantity\r\n    from trades\r\n    where date < '${__to:date}'\r\n    group by symbol\r\n  ) as totals\r\n  where quantity > 0\r\n) as shares\r\njoin (\r\n  select distinct on (symbol) symbol, adjusted_close\r\n  from market\r\n  where date < '${__to:date}'\r\n  order by symbol, date DESC\r\n) as current_prices\r\non shares.symbol = current_prices.symbol"
    }
   ]
  },
  {
   "title": "🚧[WIP] Budget🚧",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT symbol, sum(price)\nFROM trades\nWHERE date < '${__to:date}'\ngroup by symbol"
    }
   ]
  },
  { "title": "Debt", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "🚧[WIP] Breakdown🚧",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select shares.symbol, quantity * adjusted_close\r\nfrom (\r\n  select symbol, quantity\r\n  from (\r\n    select symbol, SUM(quantity) as quantity\r\n    from trades\r\n    where date < '${__to:date}'\r\n    group by symbol\r\n  ) as totals\r\n  where quantity > 0\r\n) as shares\r\njoin (\r\n  select distinct on (symbol) symbol, adjusted_close\r\n  from market\r\n  where date < '${__to:date}'\r\n  order by symbol, date DESC\r\n) as current_prices\r\non shares.symbol = current_prices.symbol"
    }
   ]
  },
  {
   "title": "🚧[WIP] Cost of Debt🚧",
   "type": "timeseries",
   "description": "Amount invested vs Portfolio Value",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select time, amount as \"Amount Invested\"\r\nfrom (\r\n    select time_bucket_gapfill('1 day', date) as time, locf(max(value)) as amount\r\n    from (\r\n      select date, SUM(invested) over (order by date) as value\r\n      from (\r\n        select trades.date, SUM(trades.quantity * lots.price) as invested\r\n        from trades\r\n        join lots on lots.id=trades.lot_id\r\n        where trades.date < '${__to:date}'\r\n        group by trades.date\r\n        order by trades.date\r\n      ) as invested_over_time\r\n    ) as cumulative\r\n    where date between '${epoch:date}' and '${__to:date}'\r\n    group by time\r\n    order by time\r\n) as history\r\nwhere $__timeFilter(time)"
    },
    {
     "rawSql": "select time, value as \"Portfolio Value\"\r\nfrom (\r\n    select time, sum(qty * price) as value\r\n    from (\r\n        select time_bucket_gapfill('1 day', date) as time, symbol, locf(min(qty)) as qty\r\n        from (\r\n            select date, symbol, SUM(quantity) over (partition by symbol order by date) as qty\r\n            from trades\r\n            where date < '${__to:date}'\r\n            order by date\r\n        ) as cumulatives\r\n        where date between '${epoch:date}' and '${__to:date}'\r\n        group by time, symbol\r\n        order by time\r\n    ) as assets\r\n    join (\r\n      select time_bucket_gapfill('1 day', date) as gapfill_date, symbol, locf(min(adjusted_close)) as price\r\n      from market\r\n      where date between '${epoch:date}' and '${__to:date}'\r\n      group by gapfill_date, symbol\r\n      order by gapfill_date\r\n    ) as extended_market\r\n    on assets.symbol=extended_market.symbol and assets.time=extended_market.gapfill_date\r\n    where qty is not null\r\n    group by time\r\n    order by time\r\n) as history\r\nwhere $__timeFilter(time)"
    }
   ]
  },
  { "title": "Retirement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "🚧[WIP] Allocations🚧",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select shares.symbol, quantity * adjusted_close\r\nfrom (\r\n  select symbol, quantity\r\n  from (\r\n    select symbol, SUM(quantity) as quantity\r\n    from trades\r\n    where date < '${__to:date}'\r\n    group by symbol\r\n  ) as totals\r\n  where quantity > 0\r\n) as shares\r\njoin (\r\n  select distinct on (symbol) symbol, adjusted_close\r\n  from market\r\n  where date < '${__to:date}'\r\n  order by symbol, date DESC\r\n) as current_prices\r\non shares.symbol = current_prices.symbol"
    }
   ]
  },
  {
   "title": "🚧[WIP] Portfolio Performance🚧",
   "type": "timeseries",
   "description": "Amount invested vs Portfolio Value",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select time, amount as \"Amount Invested\"\r\nfrom (\r\n    select time_bucket_gapfill('1 day', date) as time, locf(max(value)) as amount\r\n    from (\r\n      select date, SUM(invested) over (order by date) as value\r\n      from (\r\n        select trades.date, SUM(trades.quantity * lots.price) as invested\r\n        from trades\r\n        join lots on lots.id=trades.lot_id\r\n        where trades.date < '${__to:date}'\r\n        group by trades.date\r\n        order by trades.date\r\n      ) as invested_over_time\r\n    ) as cumulative\r\n    where date between '${epoch:date}' and '${__to:date}'\r\n    group by time\r\n    order by time\r\n) as history\r\nwhere $__timeFilter(time)"
    },
    {
     "rawSql": "select time, value as \"Portfolio Value\"\r\nfrom (\r\n    select time, sum(qty * price) as value\r\n    from (\r\n        select time_bucket_gapfill('1 day', date) as time, symbol, locf(min(qty)) as qty\r\n        from (\r\n            select date, symbol, SUM(quantity) over (partition by symbol order by date) as qty\r\n            from trades\r\n            where date < '${__to:date}'\r\n            order by date\r\n        ) as cumulatives\r\n        where date between '${epoch:date}' and '${__to:date}'\r\n        group by time, symbol\r\n        order by time\r\n    ) as assets\r\n    join (\r\n      select time_bucket_gapfill('1 day', date) as gapfill_date, symbol, locf(min(adjusted_close)) as price\r\n      from market\r\n      where date between '${epoch:date}' and '${__to:date}'\r\n      group by gapfill_date, symbol\r\n      order by gapfill_date\r\n    ) as extended_market\r\n    on assets.symbol=extended_market.symbol and assets.time=extended_market.gapfill_date\r\n    where qty is not null\r\n    group by time\r\n    order by time\r\n) as history\r\nwhere $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "🚧[WIP] ROI🚧",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select ((current_value - total_cost) / total_cost) as percent_gl, (current_value - total_cost) as total_gl\r\nfrom (\r\n    select SUM(total_cost) as total_cost, SUM(quantity * price) as current_value\r\n    from (\r\n        select trades.symbol, SUM(quantity) as quantity, SUM(quantity * lots.price) as total_cost\r\n        from trades\r\n        join lots on lots.id=trades.lot_id\r\n        where trades.date < '${__to:date}'\r\n        group by trades.symbol\r\n    ) as interm\r\n    join (\r\n        select distinct on (symbol) symbol, adjusted_close as price\r\n        from market\r\n        where date <= '${__to:date}'\r\n        order by symbol, date DESC\r\n    ) as current_prices\r\n    on interm.symbol=current_prices.symbol\r\n    where quantity > 0\r\n) as calcd\r\n"
    }
   ]
  },
  {
   "title": "🚧[WIP] Deltas🚧",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "rawSql": "with total as (\r\n    select SUM(quantity) as qty\r\n    from trades\r\n    where date <= '${__to:date}'\r\n)\r\n\r\nselect symbol as \"Symbol\", (percent_change * quantity / total.qty) as \"Impact\", percent_change as \"%Δ\", change_per_share as \"$Δ per share\", total_change as \"Total $Δ\"\r\nfrom (\r\n  select symbol, quantity,((current_value - total_cost) / total_cost) as percent_change, (current_price_per_share - avg_cost_per_share) as change_per_share, (current_value - total_cost) as total_change\r\n  from (\r\n      select interm.symbol, quantity, total as total_cost, (quantity * price) as current_value, (total / quantity) as avg_cost_per_share, price as current_price_per_share\r\n      from (\r\n          select trades.symbol, SUM(quantity) as quantity, SUM(quantity * lots.price) as total\r\n          from trades\r\n          join lots on lots.id=trades.lot_id\r\n          where trades.date <= '${__to:date}'\r\n          group by trades.symbol\r\n      ) as interm\r\n      join (\r\n          select distinct on (symbol) symbol, adjusted_close as price\r\n          from market\r\n          where date <= '${__to:date}'\r\n          order by symbol, date DESC\r\n      ) as current_prices\r\n      on interm.symbol=current_prices.symbol\r\n      where quantity > 0\r\n  ) as calcd\r\n) as calcd2 , total\r\norder by \"Impact\" desc"
    }
   ]
  }
 ]
}